[package]
name = "amazons_godot_binding"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
amazons_core = { path = "../core" }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
